ores:
  wood:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  stone:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  coal:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  copper:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  iron:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  gold:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  redstone:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  lapis:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  emerald:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  diamond:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8
  netherite:
    1: 48
    2: 32
    3: 24
    4: 16
    5: 12
    6: 8

shop:
  tools:
    wood:
      1: 2
      2: 2
      3: 2
      4: 2
      5: 2
      6: 2